Repository G-Epitech/AFMY-Seminar, pull requests merged in 2024-09, with the labels that each got.

#1 Fix Epitech's repository link in readme
  README.md
Labels: documentation

#3 docs: fix missing space in README.md authors
  README.md
Labels: documentation

#14 Fix project dependencies and packages
  apps/back/package.json
  apps/front/package-lock.json
  apps/front/package.json
  package-lock.json
  package.json
  packages/common/package.json
Labels: bug

#13 SEM 6 - Setup docker
  .env.example
  README.md
  apps/back/Dockerfile
  apps/back/package.json
  apps/front/Dockerfile
  docker-compose.yml
  package.json
Labels: documentation, Feature

#16 feat: update docker structure env files
  .gitignore
  README.md
  apps/back/.env.example
  apps/back/.gitignore
  apps/front/.env.example
  apps/front/.gitignore
  database/.env.example
  docker-compose.yml
  package.json
Labels: documentation, Feature

#20 SEM-11 - Fix Docker integration
  apps/back/Dockerfile
  apps/back/src/app/app.module.ts
  apps/back/src/main.ts
  apps/front/Dockerfile
  docker-compose.yml
  package.json
Labels: bug, DevOps

#36 SEM-18 - Add legacy API fetching system
  apps/back/.env.example
  apps/back/package.json
  apps/back/src/app/app.module.ts
  apps/back/src/classes/legacy-api/legacy-api-error.ts
  apps/back/src/providers/legacy-api/legacy-api.module.ts
  apps/back/src/providers/legacy-api/legacy-api.service.ts
  apps/back/src/types/legacy-api/dtos/index.ts
  apps/back/src/types/legacy-api/endpoints.type.ts
  apps/back/src/types/legacy-api/response.type.ts
  apps/back/src/utils/http.ts
  package-lock.json
Labels: enhancement, Feature

#43 SEM-10 - Setup employees authentication
  apps/back/.env.example
  apps/back/package.json
  apps/back/prisma/migrations/20240903134317_add_legacy_ids/migration.sql
  apps/back/prisma/migrations/20240903134755_set_legacy_ids_optionals/migration.sql
  apps/back/prisma/schema.prisma
  apps/back/src/app/app.module.ts
  apps/back/src/classes/errors/fields.error.ts
  apps/back/src/constants/auth/index.ts
  apps/back/src/constants/auth/token-expirations.ts
  apps/back/src/constants/auth/token-types.enum.ts
  apps/back/src/interceptors/response.interceptor.ts
  apps/back/src/main.ts
  apps/back/src/modules/auth/auth.controller.ts
  apps/back/src/modules/auth/auth.employee.context.ts
  apps/back/src/modules/auth/auth.module.ts
  apps/back/src/modules/auth/auth.service.ts
  apps/back/src/modules/auth/decorators/public.decorator.ts
  apps/back/src/modules/auth/dtos/auth-login.dto.ts
  apps/back/src/modules/auth/guards/jwt-auth.guard.ts
  apps/back/src/modules/employees/decorators/allow.decorator.ts
  apps/back/src/modules/employees/employees.module.ts
  apps/back/src/modules/employees/employees.service.ts
  apps/back/src/modules/employees/guards/permissions.guard.ts
  apps/back/src/providers/legacy-api/legacy-api.service.ts
  apps/back/src/types/auth/payload.type.ts
  apps/back/src/types/employees/candidates.ts
  apps/back/src/types/employees/employee-with-credentials.ts
  apps/back/src/types/employees/index.ts
  apps/back/src/types/legacy-api/endpoints.type.ts
  apps/back/src/utils/database-convertors.ts
  apps/back/src/utils/index.ts
  package-lock.json
  packages/common/src/types/clothe.type.ts
  packages/common/src/types/customer.type.ts
  packages/common/src/types/employee.type.ts
  packages/common/src/types/encounter.type.ts
  packages/common/src/types/event.type.ts
  packages/common/src/types/tip.type.ts
Labels: enhancement, Feature

#55 SEM-13 Customers routes
  apps/back/.eslintrc.js
  apps/back/prisma/migrations/20240903155636_fix_typo_in_payment_table/migration.sql
  apps/back/prisma/migrations/20240904094508_optional_coach_assignation/migration.sql
  apps/back/prisma/migrations/20240904123718_add_photo_formats_to_employees_and_customers/migration.sql
  apps/back/prisma/schema.prisma
  apps/back/src/app/app.module.ts
  apps/back/src/main.ts
  apps/back/src/modules/customers/customers.controller.ts
  apps/back/src/modules/customers/customers.module.ts
  apps/back/src/modules/customers/customers.service.ts
  apps/back/src/providers/index.ts
  apps/back/src/providers/prisma/index.ts
  apps/back/src/providers/prisma/prisma.service.ts
  apps/back/src/types/customers/candidates.ts
  apps/back/src/types/customers/index.ts
  apps/back/src/utils/database-convertors.ts
  package-lock.json
  packages/common/package.json
  packages/common/src/dtos/customers/delete-customer-clothe.dto.ts
  packages/common/src/dtos/customers/delete-customer-encounter.dto.ts
  packages/common/src/dtos/customers/delete-customer-payment.dto.ts
  packages/common/src/dtos/customers/delete-customer.dto.ts
  packages/common/src/dtos/customers/get-customer-clothes.dto.ts
  packages/common/src/dtos/customers/get-customer-encounters.dto.ts
  packages/common/src/dtos/customers/get-customer-payements.dto.ts
  packages/common/src/dtos/customers/get-customer.dto.ts
  packages/common/src/dtos/customers/get-customers.dto.ts
  packages/common/src/dtos/customers/index.ts
  packages/common/src/dtos/customers/patch-update-customer-clothe.dto.ts
  packages/common/src/dtos/customers/patch-update-customer-encounter.dto.ts
  packages/common/src/dtos/customers/patch-update-customer-payment.dto.ts
  packages/common/src/dtos/customers/patch-update-customer.dto.ts
  packages/common/src/dtos/customers/post-create-customer-clothe.dto.ts
  packages/common/src/dtos/customers/post-create-customer-encounter.dto.ts
  packages/common/src/dtos/customers/post-create-customer-payment.dto.ts
  packages/common/src/dtos/customers/post-create-customer.dto.ts
  packages/common/src/index.ts
  packages/common/src/types/clothe.type.ts
  packages/common/src/types/customer.type.ts
  packages/common/src/types/employee.type.ts
  packages/common/src/types/index.ts
  packages/common/tsconfig.json
Labels: Feature

#58 SEM-30 - Migrate employees data on login
  apps/back/.env.example
  apps/back/src/constants/auth/token-expirations.ts
  apps/back/src/constants/auth/token-types.enum.ts
  apps/back/src/modules/auth/auth.controller.ts
  apps/back/src/modules/auth/auth.employee.context.ts
  apps/back/src/modules/auth/auth.service.ts
  apps/back/src/modules/auth/decorators/public.decorator.ts
  apps/back/src/modules/auth/dtos/auth-login.dto.ts
  apps/back/src/modules/customers/customers.controller.ts
  apps/back/src/modules/employees/decorators/allow.decorator.ts
  apps/back/src/modules/employees/employees-migration.service.ts
  apps/back/src/modules/employees/employees.module.ts
  apps/back/src/modules/employees/employees.service.ts
  apps/back/src/modules/employees/guards/permissions.guard.ts
  apps/back/src/providers/legacy-api/legacy-api-convertors.ts
  apps/back/src/types/auth/payload.type.ts
  apps/back/src/types/employees/employee-with-legacy-data.ts
  apps/back/src/types/employees/index.ts
  apps/back/src/types/legacy-api/dtos/index.ts
  apps/back/src/types/legacy-api/gender.type.ts
  package-lock.json
  packages/common/src/dtos/auth/index.ts
  packages/common/src/dtos/auth/post-auth-login.dto.ts
  packages/common/src/dtos/index.ts
  packages/common/src/index.ts
  packages/common/src/types/customer.type.ts
Labels: enhancement, Feature

#61 SEM-45 - Employees 'me' route and employees photos
  apps/back/src/app/app.module.ts
  apps/back/src/interceptors/response.interceptor.ts
  apps/back/src/modules/auth/auth.service.ts
  apps/back/src/modules/employees/employees-migration.service.ts
  apps/back/src/modules/employees/employees.controller.ts
  apps/back/src/modules/employees/employees.module.ts
  apps/back/src/modules/employees/employees.service.ts
  package.json
  packages/common/src/dtos/employees/get-employee-photo.dto.ts
  packages/common/src/dtos/employees/get-me.dto.ts
  packages/common/src/dtos/employees/index.ts
  packages/common/src/dtos/index.ts
Labels: enhancement, Feature

#62 SEM-29 - Login page
  apps/front/src/api/auth/index.ts
  apps/front/src/api/auth/login.ts
  apps/front/src/api/call.ts
  apps/front/src/api/index.ts
  apps/front/src/app/coaches/layout.tsx
  apps/front/src/app/customers/layout.tsx
  apps/front/src/app/layout.tsx
  apps/front/src/app/login/page.tsx
  apps/front/src/auth/credentials.ts
  apps/front/src/components/menus/main.tsx
  apps/front/src/components/text/title.tsx
  apps/front/src/lib/config.ts
  apps/front/tailwind.config.js
Labels: Feature

#65 SEM-40 Compatibility route
  apps/back/src/modules/customers/compatiblity.service.ts
  apps/back/src/modules/customers/customers.controller.ts
  apps/back/src/modules/customers/customers.module.ts
  apps/back/src/modules/permissions/permissions.module.ts
  apps/back/src/modules/permissions/permissions.service.ts
  packages/common/src/constants/compatibility-scores.ts
  packages/common/src/constants/index.ts
  packages/common/src/dtos/customers/get-customer-compatibility.dto.ts
  packages/common/src/dtos/customers/index.ts
  packages/common/src/types/compatibility.type.ts
  packages/common/src/types/index.ts
Labels: Feature

#66 SEM-43 - Closet page
  apps/front/package.json
  apps/front/src/app/customers/[id]/closet/page.tsx
  apps/front/src/app/customers/page.tsx
  apps/front/src/components/customers/closet/combination.tsx
  apps/front/src/components/customers/closet/items.tsx
  apps/front/src/components/ui/sheet.tsx
  package-lock.json
Labels: Feature

#69 SEM-23 Add filters to customer
  apps/back/src/modules/customers/customers.controller.ts
  apps/back/src/modules/customers/customers.service.ts
  apps/front/package.json
  packages/common/src/dtos/customers/get-customers.dto.ts
  packages/common/src/index.ts
  packages/common/src/types/customer.type.ts
Labels: Improvement

#70 SEM-44 - Migrate customers data on requests
  apps/back/src/modules/auth/auth.employee.context.ts
  apps/back/src/modules/customers/customers-migration.service.ts
  apps/back/src/modules/customers/customers.module.ts
  apps/back/src/modules/customers/customers.service.ts
  apps/back/src/modules/employees/employees-migration.service.ts
  apps/back/src/types/legacy-api/astrological-sign.type.ts
  apps/back/src/types/legacy-api/dtos/index.ts
  apps/back/src/utils/database-convertors.ts
  package-lock.json
  packages/common/src/dtos/customers/get-customers.dto.ts
  packages/common/src/types/customer.type.ts
Labels: enhancement, Feature

#74 SEM-51 Add date filters to customers route
  apps/back/src/modules/customers/customers.service.ts
  packages/common/src/dtos/customers/get-customers.dto.ts
  packages/common/src/types/customer.type.ts
Labels: Improvement

#76 SEM-48 Improve responses payloads by replacing photos by their link
  apps/back/src/modules/customers/customers.controller.ts
  apps/back/src/modules/employees/employees.controller.ts
  packages/common/src/dtos/employees/get-me.dto.ts
Labels: Improvement

#77 SEM-49 - Add clothes migrations
  apps/back/src/modules/customers/customers-migration.service.ts
  apps/back/src/modules/customers/customers.controller.ts
  apps/back/src/modules/customers/customers.service.ts
  apps/back/src/providers/legacy-api/legacy-api-convertors.ts
  apps/back/src/types/legacy-api/clothe-type.type.ts
  apps/back/src/types/legacy-api/dtos/index.ts
Labels: enhancement, Feature

#81 SEM-41 Restrict all user routes
  apps/back/src/modules/customers/customers.controller.ts
  apps/back/src/modules/permissions/permissions.service.ts
Labels: Feature

#85 SEM-57 Fix customers filters
  apps/back/src/modules/customers/customers.controller.ts
  apps/back/src/modules/customers/customers.service.ts
  packages/common/src/dtos/customers/get-customers.dto.ts
  packages/common/src/types/customer.type.ts
Labels: bug

#87 SEM-22 Isolate customers country
  apps/back/prisma/migrations/20240905225054_add_country_field_in_customer/migration.sql
  apps/back/prisma/schema.prisma
  apps/back/src/modules/customers/customers-migration.service.ts
  apps/back/src/modules/customers/customers.controller.ts
  apps/back/src/modules/customers/customers.service.ts
  packages/common/src/dtos/customers/patch-update-customer.dto.ts
  packages/common/src/dtos/customers/post-create-customer.dto.ts
  packages/common/src/types/customer.type.ts
Labels: Improvement

#89 SEM-53 - Migrate encounters on requests
  apps/back/src/modules/customers/customers-migration.service.ts
  apps/back/src/modules/customers/customers.service.ts
  apps/back/src/types/legacy-api/endpoints.type.ts
Labels: enhancement, Feature

#90 SEM-58 - link customer clothes
  apps/front/src/api/customers/clothes.ts
  apps/front/src/api/customers/index.ts
  apps/front/src/api/customers/list.ts
  apps/front/src/app/customers/[id]/closet/page.tsx
  apps/front/src/components/customers/closet/combination.tsx
  apps/front/src/components/customers/closet/items.tsx
  package-lock.json
Labels: Feature

#93 SEM-60 - Improve Dockerfiles
  apps/back/Dockerfile
  apps/front/Dockerfile
Labels: DevOps, Improvement

#94 SEM-54 Create statistics module
  apps/back/src/app/app.module.ts
  apps/back/src/modules/statistics/statistics.controller.ts
  apps/back/src/modules/statistics/statistics.module.ts
  apps/back/src/modules/statistics/statistics.service.ts
  package-lock.json
  packages/common/src/dtos/index.ts
  packages/common/src/dtos/statistics/get-statistics.dto.ts
  packages/common/src/dtos/statistics/index.ts
  packages/common/src/types/index.ts
  packages/common/src/types/statistics.type.ts
Labels: Feature

#98 SEM-52 & SEM-55 - Create route to get images via tokens
  apps/back/src/app/app.module.ts
  apps/back/src/modules/auth/auth.module.ts
  apps/back/src/modules/customers/customers-migration.service.ts
  apps/back/src/modules/customers/customers.controller.ts
  apps/back/src/modules/customers/customers.module.ts
  apps/back/src/modules/customers/customers.service.ts
  apps/back/src/modules/employees/employees.controller.ts
  apps/back/src/modules/employees/employees.module.ts
  apps/back/src/modules/images/images.controller.ts
  apps/back/src/modules/images/images.module.ts
  apps/back/src/modules/images/images.service.ts
  apps/back/src/types/images/image-token.type.ts
  apps/back/src/types/images/image-typed.type.ts
  apps/back/src/types/images/index.ts
  packages/common/src/dtos/images/get-image.dto.ts
  packages/common/src/dtos/images/index.ts
  packages/common/src/dtos/index.ts
Labels: enhancement, Feature

#101 SEM-33 - Dashboard page
  .gitattributes
  apps/back/package.json
  apps/back/prisma/seed.ts
  apps/front/Dockerfile
  apps/front/package.json
  apps/front/public/world-map.json
  apps/front/src/api/index.ts
  apps/front/src/api/statistics/get.ts
  apps/front/src/api/statistics/index.ts
  apps/front/src/app/coaches/page.tsx
  apps/front/src/app/dashboard/layout.tsx
  apps/front/src/app/dashboard/page.tsx
  apps/front/src/app/globals.css
  apps/front/src/app/layout.tsx
  apps/front/src/components/dashboard/charts/customers.tsx
  apps/front/src/components/dashboard/charts/events.tsx
  apps/front/src/components/dashboard/charts/map.tsx
  apps/front/src/components/dashboard/charts/meetings.tsx
  apps/front/src/components/dashboard/charts/metrics.tsx
  apps/front/src/components/dashboard/charts/utils.tsx
  apps/front/src/components/icons/events.tsx
  apps/front/src/components/icons/payments.tsx
  apps/front/src/components/text/subtitle.tsx
  package-lock.json
  packages/common/src/dtos/customers/patch-update-customer-encounter.dto.ts
  packages/common/src/dtos/customers/patch-update-customer-payment.dto.ts
  packages/common/src/dtos/customers/patch-update-customer.dto.ts
  packages/common/src/dtos/customers/post-create-customer-encounter.dto.ts
  packages/common/src/dtos/customers/post-create-customer-payment.dto.ts
  packages/common/src/dtos/customers/post-create-customer.dto.ts
Labels: Feature

#102 SEM-61 Add statistics migration
  apps/back/prisma/migrations/20240906122332_unique_locations/migration.sql
  apps/back/prisma/schema.prisma
  apps/back/src/modules/customers/customers-migration.service.ts
  apps/back/src/modules/customers/customers.module.ts
  apps/back/src/modules/employees/employees-migration.service.ts
  apps/back/src/modules/statistics/statistics-migration.service.ts
  apps/back/src/modules/statistics/statistics.controller.ts
  apps/back/src/modules/statistics/statistics.module.ts
Labels: Feature

#103 SEM-12 - Add employees routes
  apps/back/prisma/schema.prisma
  apps/back/src/modules/employees/employees-migration.service.ts
  apps/back/src/modules/employees/employees.controller.ts
  apps/back/src/modules/employees/employees.module.ts
  apps/back/src/modules/employees/employees.service.ts
  apps/back/src/modules/permissions/permissions.module.ts
  apps/back/src/modules/permissions/permissions.service.ts
  apps/back/src/modules/statistics/statistics-migration.service.ts
  apps/back/src/types/employees/candidates.ts
  package-lock.json
  packages/common/src/dtos/employees/delete-employee.dto.ts
  packages/common/src/dtos/employees/get-employee-photo.dto.ts
  packages/common/src/dtos/employees/get-employee.dto.ts
  packages/common/src/dtos/employees/get-employees.dto.ts
  packages/common/src/dtos/employees/index.ts
  packages/common/src/dtos/employees/patch-employee.dto.ts
  packages/common/src/types/employee.type.ts
Labels: enhancement, Feature

#106 SEM-64 fix backend issues with employees id and statistic migration
  CODEOWNERS
  apps/back/src/modules/employees/employees-migration.service.ts
  apps/back/src/modules/statistics/statistics-migration.service.ts
  apps/back/src/modules/statistics/statistics.controller.ts
  package.json
Labels: bug

#108 SEM-34 - Add create button
  apps/back/package.json
  apps/back/src/modules/customers/customers.controller.ts
  apps/back/src/modules/images/images.service.ts
  apps/front/package.json
  apps/front/src/app/customers/page.tsx
  apps/front/src/app/globals.css
  apps/front/src/components/ui/avatar.tsx
  apps/front/src/components/ui/calendar.tsx
  apps/front/src/components/ui/date-picker.tsx
  apps/front/src/components/ui/popover.tsx
  apps/front/src/components/ui/scroll-area.tsx
  apps/front/src/components/ui/select.tsx
  package-lock.json
  packages/common/src/dtos/customers/post-create-customer.dto.ts
Labels: Feature

#109 SEM-56 - Link all api endpoints to pages
  apps/back/src/modules/customers/customers.controller.ts
  apps/back/src/modules/employees/employees.controller.ts
  apps/back/src/modules/employees/employees.service.ts
  apps/front/src/api/customers/count.ts
  apps/front/src/api/customers/encounters/index.ts
  apps/front/src/api/customers/encounters/list.ts
  apps/front/src/api/customers/get.ts
  apps/front/src/api/customers/index.ts
  apps/front/src/api/customers/payments/index.ts
  apps/front/src/api/customers/payments/list.ts
  apps/front/src/api/employees/count.ts
  apps/front/src/api/employees/index.ts
  apps/front/src/api/employees/list.ts
  apps/front/src/app/coaches/page.tsx
  apps/front/src/app/customers/[id]/page.tsx
  apps/front/src/app/customers/page.tsx
  apps/front/src/components/coaches/table/index.tsx
  apps/front/src/components/customers/encounters/columns.tsx
  apps/front/src/components/customers/table/columns/payment.tsx
  apps/front/src/components/customers/table/index.tsx
  apps/front/src/components/table/select/footer.tsx
  apps/front/src/components/table/select/index.tsx
  packages/common/src/dtos/customers/get-customers-count.dto.ts
  packages/common/src/dtos/customers/index.ts
  packages/common/src/dtos/employees/get-employees-count.dto.ts
  packages/common/src/dtos/employees/get-employees.dto.ts
  packages/common/src/dtos/employees/index.ts
  packages/common/src/types/employee.type.ts
Labels: Feature

#124 SEM-26 Customer payment methods
  apps/back/prisma/seed.ts
  apps/back/src/modules/customers/customers-migration.service.ts
  apps/back/src/modules/customers/customers.service.ts
  apps/back/src/providers/legacy-api/legacy-api-convertors.ts
  apps/back/src/types/legacy-api/dtos/index.ts
  apps/back/src/types/legacy-api/payment-method.type.ts
  apps/front/src/components/customers/encounters/columns.tsx
  apps/front/src/components/customers/payments/columns.tsx
Labels: Improvement

#127 SEM-78 Customer closet
  apps/front/public/zodiac-signs/aquarius.svg
  apps/front/public/zodiac-signs/aries.svg
  apps/front/public/zodiac-signs/cancer.svg
  apps/front/public/zodiac-signs/capricorn.svg
  apps/front/public/zodiac-signs/gemini.svg
  apps/front/public/zodiac-signs/leo.svg
  apps/front/public/zodiac-signs/libra.svg
  apps/front/public/zodiac-signs/pisces.svg
  apps/front/public/zodiac-signs/sagittarius.svg
  apps/front/public/zodiac-signs/scorpio.svg
  apps/front/public/zodiac-signs/taurus.svg
  apps/front/public/zodiac-signs/virgo.svg
  apps/front/src/app/compatibility/page.tsx
  apps/front/src/app/compatibility/radar.tsx
  apps/front/src/app/customers/[id]/page.tsx
  apps/front/src/components/compatibility/select.tsx
  apps/front/src/components/compatibility/zodiac-sign.tsx
  apps/front/src/components/customers/closet/combination.tsx
  apps/front/src/components/customers/closet/items.tsx
Labels: Improvement

#131 Delete customers from table
  apps/front/package.json
  apps/front/src/api/customers/delete.ts
  apps/front/src/api/customers/index.ts
  apps/front/src/app/customers/page.tsx
  apps/front/src/components/customers/table/actions.tsx
  apps/front/src/components/customers/table/index.tsx
  apps/front/src/components/ui/alert-dialog.tsx
  package-lock.json
Labels: Feature

#132 SEM-71 - Delete coaches from table
  apps/front/src/api/employees/delete.ts
  apps/front/src/api/employees/index.ts
  apps/front/src/app/coaches/page.tsx
  apps/front/src/components/coaches/table/actions.tsx
  apps/front/src/components/coaches/table/index.tsx
Labels: Feature

#133 SEM-77 - Fix customers and coaches search
  apps/front/src/app/coaches/page.tsx
  apps/front/src/app/customers/page.tsx
  apps/front/src/components/coaches/table/index.tsx
  apps/front/src/components/customers/table/index.tsx
  apps/front/src/components/table/select/filters.tsx
  apps/front/src/components/table/select/index.tsx
  packages/common/src/dtos/customers/get-customers.dto.ts
  packages/common/src/dtos/employees/get-employees.dto.ts
Labels: Feature

#134 SEM-37 / SEM-39 Events page
  apps/back/prisma/migrations/20240911225021_fix_events_dates/migration.sql
  apps/back/prisma/schema.prisma
  apps/back/prisma/seed.ts
  apps/back/src/app/app.module.ts
  apps/back/src/modules/customers/customers.controller.ts
  apps/back/src/modules/employees/employees.controller.ts
  apps/back/src/modules/events/events-migration.service.ts
  apps/back/src/modules/events/events.controller.ts
  apps/back/src/modules/events/events.module.ts
  apps/back/src/modules/events/events.service.ts
  apps/back/src/modules/statistics/statistics-migration.service.ts
  apps/back/src/modules/statistics/statistics.service.ts
  apps/back/src/types/events/candidates.ts
  apps/back/src/types/events/index.ts
  apps/front/src/api/events/index.ts
  apps/front/src/api/events/list.ts
  apps/front/src/api/index.ts
  apps/front/src/app/events/layout.tsx
  apps/front/src/app/events/page.tsx
  apps/front/tsconfig.json
  package-lock.json
  package.json
  packages/common/src/dtos/events/get-events.dto.ts
  packages/common/src/dtos/events/index.ts
  packages/common/src/dtos/events/patch-event.dto.ts
  packages/common/src/dtos/index.ts
  packages/common/src/types/event.type.ts
Labels: Feature

#137 SEM-82 Tips module
  apps/back/src/app/app.module.ts
  apps/back/src/modules/tips/tips-migration.service.ts
  apps/back/src/modules/tips/tips.controller.ts
  apps/back/src/modules/tips/tips.module.ts
  apps/back/src/modules/tips/tips.service.ts
  apps/back/src/types/tips/candidate.ts
  apps/back/src/types/tips/index.ts
  apps/front/src/api/index.ts
  apps/front/src/api/tips/get.ts
  apps/front/src/api/tips/index.ts
  apps/front/src/api/tips/list.ts
  apps/front/src/app/tips/page.tsx
  packages/common/src/dtos/index.ts
  packages/common/src/dtos/tips/get-tips.dto.ts
  packages/common/src/dtos/tips/index.ts
  packages/common/src/dtos/tips/patch-tip.dto.ts
  packages/common/src/dtos/tips/post-create-tip.dto.ts
Labels: Feature

#138 SEM-35 - Add coach profile page
  apps/back/src/modules/auth/auth.service.ts
  apps/back/src/modules/customers/customers-migration.service.ts
  apps/back/src/modules/employees/employees-migration.service.ts
  apps/back/src/modules/employees/employees.controller.ts
  apps/back/src/modules/employees/employees.service.ts
  apps/back/src/providers/legacy-api/legacy-api.service.ts
  apps/front/src/api/customers/index.ts
  apps/front/src/api/customers/update.ts
  apps/front/src/api/employees/customers.ts
  apps/front/src/api/employees/get.ts
  apps/front/src/api/employees/index.ts
  apps/front/src/api/employees/list.ts
  apps/front/src/app/coaches/[id]/page.tsx
  apps/front/src/app/coaches/page.tsx
  apps/front/src/components/coaches/customers/dialogs/assign.tsx
  apps/front/src/components/coaches/customers/dialogs/index.ts
  apps/front/src/components/coaches/customers/dialogs/unassign.tsx
  apps/front/src/components/coaches/customers/index.ts
  apps/front/src/components/coaches/customers/table/columns/actions.tsx
  apps/front/src/components/coaches/customers/table/columns/customer.tsx
  apps/front/src/components/coaches/customers/table/columns/email.tsx
  apps/front/src/components/coaches/customers/table/columns/index.tsx
  apps/front/src/components/coaches/customers/table/columns/phone.tsx
  apps/front/src/components/coaches/customers/table/index.tsx
  apps/front/src/components/coaches/profile.tsx
  apps/front/src/components/coaches/table/columns/coach.tsx
  apps/front/src/components/coaches/table/columns/index.tsx
  apps/front/src/components/coaches/table/index.tsx
  apps/front/src/components/customers/profile.tsx
  apps/front/src/components/customers/table/index.tsx
  apps/front/src/components/menus/main.tsx
  apps/front/src/components/table/infinite/body.tsx
  apps/front/src/components/table/infinite/filters.tsx
  apps/front/src/components/table/infinite/footer.tsx
  apps/front/src/components/table/infinite/header.tsx
  apps/front/src/components/table/infinite/index.tsx
  apps/front/src/components/table/select/body.tsx
  apps/front/src/components/table/select/index.tsx
  apps/front/src/components/ui/autocomplete.tsx
  apps/front/src/components/ui/command.tsx
  package-lock.json
  packages/common/src/dtos/customers/patch-update-customer.dto.ts
  packages/common/src/dtos/employees/get-employee-customers.dto.ts
  packages/common/src/dtos/employees/index.ts
Labels: bug, enhancement, Feature

#140 SEM-67 - Create a coach
  apps/back/.env.example
  apps/back/package.json
  apps/back/prisma/schema.prisma
  apps/back/src/modules/auth/auth.controller.ts
  apps/back/src/modules/auth/auth.module.ts
  apps/back/src/modules/auth/auth.service.ts
  apps/back/src/modules/auth/mail.service.ts
  apps/back/src/modules/employees/employees.controller.ts
  apps/back/src/modules/employees/employees.module.ts
  apps/back/src/modules/employees/employees.service.ts
  apps/front/src/api/auth/forgot-password.ts
  apps/front/src/api/auth/index.ts
  apps/front/src/api/auth/reset-password.ts
  apps/front/src/app/auth/forgot-password/page.tsx
  apps/front/src/app/auth/login/page.tsx
  apps/front/src/app/auth/reset-password/page.tsx
  apps/front/src/app/coaches/page.tsx
  apps/front/src/app/page.tsx
  apps/front/src/components/menus/main.tsx
  apps/front/src/components/menus/user.tsx
  package-lock.json
  packages/common/src/dtos/auth/index.ts
  packages/common/src/dtos/auth/post-auth-forgot-password.dto.ts
  packages/common/src/dtos/auth/post-auth-reset-password.dto.ts
  packages/common/src/dtos/employees/index.ts
  packages/common/src/dtos/employees/post-create-employee.dto.ts
Labels: Feature

#144 SEM-84 Assign customers on creation
  apps/back/src/modules/customers/customers.controller.ts
Labels: Improvement

#141 SEM-83 - Show filtered count on customers page when user is a coach
  apps/back/src/modules/customers/customers.controller.ts
  apps/back/src/modules/customers/customers.service.ts
  package-lock.json
Labels: bug

#149 SEM-81 - Add link to coach profile in customer profile
  apps/front/src/app/customers/[id]/page.tsx
  apps/front/src/components/customers/profile.tsx
Labels: enhancement, Feature

#154 SEM-91 - Add forgot password link
  apps/back/prisma/seed.ts
  apps/back/src/modules/statistics/statistics.service.ts
  apps/front/src/app/auth/login/page.tsx
  package-lock.json
Labels: Feature
